name: "Hello World"
description: "Greet someone there"
inputs:
  apiKey:
    description: "API key from Whitesource."
    required: true
  productName:
    description: "Name of the Product that this project falls under."
    required: false
  projectName:
    description: "Name of the Project. It could be just repository name. Default: Repository Name without owner."
    required: false
  configFile:
    description: "Filename of whitesource configuration if being used (including file path)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout files
      uses: actions/checkout@v3

    - name: Run scanner
      env:
        WS_APIKEY: ${{inputs.apiKey}}
        WS_WSSURL: https://saas.whitesourcesoftware.com/agent
        WS_PROJECTNAME: ${{inputs.projectName}}
        WS_PRODUCTNAME: ${{inputs.productName}}
        WS_CONFIGFILE: ${{inputs.configFile}}
      run: ${{ github.action_path }}/wss.sh
      shell: bash

    - name: Whitesource Scan error
      if: ${{env.ws_scan_error}}
      env:
        MESSAGE: ${{env.ws_scan_error}}
      run: echo "$MESSAGE" >> "$GITHUB_STEP_SUMMARY"
      shell: bash
